sudo: required

services:
   - docker

before_install:
   - docker build -t pionuxos/mflinger .

script:
   - docker run pionuxos/mflinger /bin/bash -c "cd mflinger && make"
   - docker run pionuxos/mflinger /bin/bash -c "cd mflinger && make tests && ./tests/suite"
